---
tags: ["Algos","Needs-Tests","Timeseries","alignment","data-analysis","data-science","flexible","pandas","python"]
title: "BUG: AttributeError: 'DatetimeArray' object has no attribute 'notna' in pandas 2.1.1"
html_url: "https://github.com/pandas-dev/pandas/issues/55431"
user: "davidboweninrupt"
repo: "pandas-dev/pandas"
---

